pipeline {
	agent any

    triggers {
		githubPush()
    }

    stages {
		stage('Docker Compose Build') {
			steps {
				bat 'cd onboarding && docker-compose down --volumes --remove-orphans'
                bat 'cd onboarding && docker-compose build'
            }
        }

        stage('Run App with Docker Compose') {
			steps {
				bat 'cd onboarding && docker-compose up -d --force-recreate'
            }
        }
    }

    post {
		always {
			bat 'cd onboarding && docker-compose ps'
            echo 'Build pipeline finished.'
        }
    }
}

