pipeline {
	agent any

    triggers {
		githubPush()
    }

    stages {
		stage('Docker Compose Build') {
			steps {
				bat 'cd onboarding && docker-compose down --volumes --remove-orphans'
                bat 'cd onboarding && docker-compose build'
            }
        }

        stage('Run App with Docker Compose') {
			steps {
				bat 'cd onboarding && docker-compose up -d --force-recreate'
            }
        }

        stage('Health Check') {
			steps {
				script {
					def retries = 10
                    def delay = 5
                    for (int i = 0; i < retries; i++) {
						def result = bat(script: 'curl -s -o nul -w "%{http_code}" http://localhost:8080/actuator/health', returnStdout: true).trim()
                        if (result == "200") {
							echo "✅ Health check passed"
                            break
                        } else {
							echo "❌ Health check failed with status: ${result}, retrying in ${delay}s..."
                            sleep time: delay, unit: 'SECONDS'
                        }
                        if (i == retries - 1) {
							error "❌ Health check failed after ${retries} attempts"
                        }
                    }
                }
            }
        }
    }

    post {
		always {
			bat 'cd onboarding && docker-compose ps'
            echo 'Build pipeline finished.'
        }
    }
}

